style="sciml"
align_assignment=true
align_struct_field=true
always_for_in=true
whitespace_ops_in_indices=true
remove_extra_newlines=true
always_use_return=false
whitespace_in_kwargs=false
format_docstrings=true
normalize_line_endings="unix"
trailing_comma=false
separate_kwargs_with_semicolon=true
whitespace_typedefs=false
short_to_long_function_def=false