name = "SparseIR"
uuid = "fefa8bd7-c5b3-4143-ace4-737a34ae5886"
authors = ["Samuel Badr <samuel.badr@gmail.com> and contributors"]
version = "0.1.0"

[deps]
AssociatedLegendrePolynomials = "2119f1ac-fb78-50f5-8cc0-dda848ebdb19"
FastGaussQuadrature = "442a2c76-b920-505d-bb47-c5924d526838"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
