name = "SparseIR"
uuid = "4fe2279e-80f0-4adb-8463-ee114ff56b7d"
authors = ["Samuel Badr <samuel.badr@gmail.com>", "Hiroshi Shinaoka <h.shinaoka@gmail.com>", "Markus Wallerberger <markus.wallerberger@tuwien.ac.at>"]
version = "0.94.4"

[deps]
Bessels = "0e736298-9ec6-45e8-9647-e4fc86a2fe38"
GenericLinearAlgebra = "14197337-ba66-59df-a3e3-ca00e7dcff7a"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MultiFloats = "bdf0d083-296b-4888-a5b6-7498122e68a5"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"

[compat]
Bessels = "0.1, 0.2"
GenericLinearAlgebra = "0.3.1"
MultiFloats = "1"
QuadGK = "2"
julia = "1.6"

[extras]
AssociatedLegendrePolynomials = "2119f1ac-fb78-50f5-8cc0-dda848ebdb19"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["AssociatedLegendrePolynomials", "Test"]
