name = "SparseIR"
uuid = "4fe2279e-80f0-4adb-8463-ee114ff56b7d"
authors = ["SatoshiTerasaki <terasakisatoshi.math@gmail.com>", "Samuel Badr <samuel.badr@gmail.com>", "Hiroshi Shinaoka <h.shinaoka@gmail.com>", "Markus Wallerberger <markus.wallerberger@tuwien.ac.at>"]
version = "2.0.0-alpha.1"

[deps]
CEnum = "fa961155-64e5-5f13-b03f-caf6b980ea82"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
libsparseir_jll = "e5bf0e3f-5e75-5bb8-9f3f-2c07620468a3"

[compat]
Aqua = "0.8.14"
CEnum = "0.5.0"
Clang = "0.19.1"
Libdl = "1"
LinearAlgebra = "1"
QuadGK = "2.11.2"
StableRNGs = "1.0.3"
julia = "1.6"
libsparseir_jll = "0.6.0"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Clang = "40e3b903-d033-50b4-a0cc-940c62c95e31"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
ReTestItems = "817f1d60-ba6b-4fd5-9520-3cf149f6a823"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test", "ReTestItems", "Random", "StableRNGs"]
dev = ["Clang"]
